language: rust

sudo: required
dist: xenial

cache: false

rust:
  - stable
  - nightly

os:
  - linux

matrix:
  include:
    - os: windows
      python: "3.7"
      before_install:
      - export PATH="/c/Python37:/c/Python37/Scripts:/c/ProgramData/chocolatey/lib/ninja/tools:$PATH"
      - choco install python --version 3.7.4
      - python -m pip install --upgrade pip
      - choco install ninja
      - pip install numpy
      - eval "$(python vcvars_proxy.py
        'c:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/Common7/Tools/VsDevCmd.bat'
        '-arch=amd64'
        '-host_arch=amd64'
        '-vcvars_ver=14.0')"
      - export CC=cl.exe
      - export CXX=cl.exe
      - export CC_FOR_BUILD=cl.exe
      - export CXX_FOR_BUILD=cl.exe
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script:
  - rustup component add clippy

script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then cargo clippy --all                                      ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then cargo test --verbose --all                              ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then cargo build --verbose                                   ; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then cargo clippy --all --features miner-cpu                ; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then cargo test --verbose --all                             ; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then cargo build --verbose --features miner-cpu             ; fi