language: rust

sudo: required
dist: xenial

cache: cargo

rust:
  - stable
  - nightly

os:
  - windows
  - linux
  - osx

addons:
  apt:
    packages:
      - cmake
      - gcc

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - cargo test --verbose --all --features miner-cpu
  - cargo build --verbose --features miner-cpu