language: rust

sudo: required
dist: xenial

cache: false

rust:
  - stable
  - nightly

os:
  - linux
  - osx

matrix:
  include:
    - os: windows
      before_install:
      - choco install python
      - choco install ninja
      - export PATH="/c/Python37:/c/ProgramData/chocolatey/lib/ninja/tools:$PATH"
      - /c/Python37/Scripts/pip install numpy
      - eval "$(python vcvars_proxy.py
        'c:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/Common7/Tools/VsDevCmd.bat'
        '-arch=amd64'
        '-host_arch=amd64'
        '-vcvars_ver=14.0')"
      - export CC=cl.exe
      - export CXX=cl.exe
      - export CC_FOR_BUILD=cl.exe
      - export CXX_FOR_BUILD=cl.exe
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then cargo test --verbose --all                        ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then cargo build --verbose                             ; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then cargo test --verbose --all --features miner-cpu  ; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then cargo build --verbose --features miner-cpu       ; fi