[package]
name = "rpc"
version = "0.1.0"
authors = ["Cristian Șerb <cserb@pm.me>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonrpc-core = "12.0.0"
jsonrpc-http-server = "12.0.0"