[package]
name = "constants"
version = "0.1.0"
authors = ["florin30 <florin191-git@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
static_assertions = "1"